### ISSUE TITLE
some documentation issues

### ISSUE THREAD

**Issue by bew** [calebuharrison/CrystGLFW#4]
Hello, great lib!

I'm just experimenting with GLFW for the first time, and have found some documentation issues:

- `wait_events` blocking the crystal program until an event from GLFW (that you said), maybe add a note saying that for example other fibers will not run while waiting for an event.
- `Key::*` returned by a `on_key` event are wrong on non-english keyboard: For example I use an AZERTY keyboard, when I press on `q` I get a `Key::A`, but when I do `key.name` I correctly get `q`. I'm not sure this can be easily fixed, as it depends on runtime state (the keyboard layout), so it must be properly documented.

**Comment by calebuharrison** [comment]
Thanks for the notes and PRs!

I'll update the `wait_events` documentation to clarify that the entire OS thread is blocked, not the current fiber.

The key issue is baked into GLFW itself - the rationale is [here](http://www.glfw.org/docs/latest/group__keys.html).  Perhaps it would be helpful to simply link to the GLFW docs from that section of the guides?

**Comment by bew** [comment]
> The key issue is baked into GLFW itself - the rationale is here. Perhaps it would be helpful to simply link to the GLFW docs from that section of the guides?

Adding a link looks like a good idea yes! Thank you

**Comment by calebuharrison** [comment]
Thanks for your help.  The guides should be a bit more clear on these subjects now.

**Comment by bew** [comment]
The link doesn't work:
![bad_link](https://user-images.githubusercontent.com/9730330/34653888-8306aa6e-f3f3-11e7-9a47-39f0547b90fa.png)
and it's gives a 404 page not found.

Just remove the `\` and it should be good I think.

**Comment by calebuharrison** [comment]
Not sure how that got there.  Fixed.
